user mosquitto
persistence true
persistence_location /mosquitto/data/
log_dest stdout
allow_anonymous false
password_file /run/sentinel/passwords
acl_file /mosquitto/config/acl
message_size_limit 16384
max_queued_messages 1000

listener 8883
protocol mqtt
certfile /run/sentinel/server.crt
keyfile /run/sentinel/server.key
tls_version tlsv1.2

listener 9001
protocol websockets
certfile /run/sentinel/server.crt
keyfile /run/sentinel/server.key
tls_version tlsv1.2
